# Please do not remove this.
Extra-TAG: tag_r72EhIAL

# When a name in the language requested does not exist, the name will be
# retrieved in this language. The default fall back language is English.
FallbackLanguage: en_us

# If you want to enable the loading of a language, add it to the following list
# LoadLanguage: [zh_cn, zh_tw, ko_kr, ja_jp, fr_fr, ru_ru]
# Or
LoadLanguage:
    - cs_cz
    - de_de
    - es_es
    - fr_fr
    - hu_hu
    - id_id
    - it_it
    - ja_jp
    - ko_kr
    - lv_lv
    - pl_pl
    - pt_br
    - ro_ro
    - ru_ru
    - tr_tr
    - vi_vn
    - zh_cn
    - zh_tw
# If you want to load all the languages, add "all" to the list:
#     - all
